language: python
dist: trusty
sudo: required
services:
- docker
python:
- '3.6'
env:
  global:
  - FLASK_ENV=development
install:
- pip install pipenv
- pipenv install --dev
before_script:
- export MODE=CI
script:
- flake8
deploy:
- provider: script
  script: bash deploy/travis.sh
  on:
    tags: true
notifications:
  slack:
    on_success: always
    on_failure: always
    rooms:
      secure: KGhbo0lXe0XkW0HHqSzGwy1enl6qlrEaUXYocZo0Qcz+P8yykSo7h2iMti0EWeffrthg31lVUtdz/Sx9cHOi++C2ORdZuxkHSiNanMoJ4pos7yocUvcv1S79KC2IEFgGs2boY+FDxQhyn1ynR/SJRcguIrMPthJ/SuWBcWlSGwRl0GiWDx+guZtmE0t4J2Cb9EFO8DilqA9T1GZUIjsR6yADN9DqoUno7QouFpVbuU9q0uJDpOikhtQyQdmyzayCmWbylnaQ25YAkAQdOGRok+k5fukkHBGzng4Mwd65yWpwBZGE7YFQGly6U8o8caaWgSc7d45cVW23XdoSodPbQix5Fos7KM/1bJ6rG9RHp8SquT4hRZLq2q9HRYgKKxFI6V5pDOMe3fFgn4/7CbTaT2DZg+SLmY7N7JjALMq+KCbk2u4jGQnOAs7x49EsgjxeSR9QOoYe8xFirtOisewDuQ9gMBHgijBO0lZGtEKQ8qHeARBdXwpnZ7k1fjMyivYb/xopmBr4EEU+Ha5dCpcL+X4F62YrZs/kFQqWqGcacUA+IBEEf8dQoHVHWYYJNN53kh0nUgdYd+l9quJ5a6hPH4j82BZ2BchXWn3MCB753IH0pIQX2h9mDb/JGemibjpo1IeXZiJjKPWvGFcZaz5iNMLpmz60d/Oea8lICp9cEuw=
