language: python
dist: trusty
sudo: required
services:
- docker
python:
- '3.6'
env:
  global:
  - FLASK_ENV=development
install:
- pip install pipenv
- pipenv install --dev
before_script:
- export MODE=CI
script:
- flake8
deploy:
- provider: script
  script: bash deploy/travis.sh
  on:
    tags: true
notifications:
  slack:
    on_success: always
    on_failure: always
    secure: fKwLElTGSkknXnZmVes4nHqcrg8JrFq1e4QcCfu4dE+l1Va54/FJQGHe64XgRk50Fsvgt8g4ynD4P5bgiD9tZt4VexdoSHTQlBBCQSL5DNvVBwmdVOsWXf3gJNOcewRQC3rfW8/fUanFd9D8h5tkPtIr9WbDJbPeoAUxVx8bhGAgAACh2qXnW793myYYUgD2ZoK53EmlFYZpUDLgWimatpGkgdrWP+rS7zTYiTjj83zEVA9iajOcFfzoigWzNRLJyeMSEKG2dJCJaWb3JDoVZPFKDFVb0trJTHnH7A61W8RLjpDGjx0p32lEjLBgm4X4t79n5XLO7R+psVSpru4inzmeVqBvHXK2mFylhuGoVOk1lT9cMtDKu+sVjCCe9D2lDPvXoubmjtGupuC3m1JueIdZ1bldjr0VW/wWOmjKsWTR8hOwfuIG96XzxPITJ5I4ZdMX6ZhLlq3Bmznr4qg8Vx/ypIT63iT3zXEwgZ7gyq9NjcPAPH4Z4zB5qvcgljMv0i+LoE8q8Z23epJcGj42PovdoBiRvBPNACoMawbTrujoGiOLzJE5bCqVGcx+6KZYunt0Dpm6jDYBAnkpW2CGk/Bf5f/53+fSM9flM4e/SYfLaN9/kyWhN7/0jhCw6dsummgDLneDC3kELe6ZhaRFGn5U5cPo2dCetedXXdG4TZA=
